require("dotenv").config()
const express = require("express")
const app = express()
const cors = require("cors")
const signupRouter = require("./controller/signupRouter")
const loginRouter = require("./controller/loginRouter")
const userdataRouter = require("./controller/userdataRouter")
const platformRouter = require("./controller/platformRouter")
const cookieParser = require("cookie-parser")
app.use(cookieParser())
app.use(express.json())
app.use(cors({ credentials: true, origin: true }))
const mongoose = require("mongoose")
mongoose.connect(process.env.MONGO_URL)
.then(()=>{
    console.log("connected")
}).catch(()=>{
    console.log("error")
})
app.use(express.static('build'))
app.use('/api/signup',signupRouter)
app.use('/api/login',loginRouter)
app.use('/api/userdata',userdataRouter)
app.use('/api/platform',platformRouter)
module.exports=app